services:
  api:
    build:
      context: ./src/Shortener
      target: dev
    volumes:
      - ./Shortener:/src
      - nuget_cache:/root/.nuget/packages
      - /src/bin
      - /src/obj

volumes:
  nuget_cache:
