@host = http://localhost:8080

### Login (rode este primeiro; o token vale para os requests abaixo)
# @name login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "secret123"
}


### Create a short url
@token = {{login.response.body.$.token}}

POST {{host}}/api/shorturls
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "originalUrl": "https://example.com/some/long/pathss"
}

### List all short urls
GET {{host}}/api/shorturls
Accept: application/json
Authorization: Bearer {{token}}

### Get a short url by id
@id = 4
GET {{host}}/api/shorturls/{{id}}
Accept: application/json
Authorization: Bearer {{token}}
